// <auto-generated />
using Heros.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Heros.Migrations
{
    [DbContext(typeof(HeroDbContext))]
    partial class HeroDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Heros.Database.Hero", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("BirthDay")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BirthMonth")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BirthYear")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Branch")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CauseOfDeath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CountyCodeFips")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DateOfPassing")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FlagReceiveStatus")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FlagReceivedDate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FlagSponsor")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FlagStatus")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Group")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HeroType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LocationOfDeath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MiddleName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nickname")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OriginCity")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OriginCounty")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OriginCountyName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OriginDevisionCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OriginDivisionName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OriginLocation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OriginRegionCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OriginRegionName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OriginState")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OriginStateFipsCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OriginStateName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Prefix")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Rank")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Specialization")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Suffix")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TreeLatitude")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TreeLongitude")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TreeStatus")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("War")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Heroes");
                });
#pragma warning restore 612, 618
        }
    }
}
